2024-02-29 17:06:24,979 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1049' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at C:\Users\RayBe\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\tornado\websocket.py:1086> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "C:\Users\RayBe\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\tornado\websocket.py", line 1088, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RayBe\AppData\Local\NVIDIA\ChatWithRTX\env_nvd_rag\lib\site-packages\tornado\websocket.py", line 1090, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
